[build]
  base    = "apps/web"
  command = "npx ng build --configuration=production"
  publish = "dist/web/browser"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/angular-runtime"
